name: '@ocmedialab/amp - Release & Publish to npm'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release on npm (Node 22)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: npm publish --access public # Public access for the package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Reference to the secret you added to GitHub
