name: Size Check

on:
  pull_request:

jobs:
  size:
    name: Check Bundle Size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run size-limit
        run: npm run size
